package gui;

import dao.FornecedoresDAO;
import dao.PecasDAO;
import dao.PecasPedidosDAO;
import dao.PedidosDAO;
import java.sql.Connection;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdbc.MySQLConnection;
import model.Fornecedores;
import model.Pecas;
import model.PecasPedidos;
import model.Pedidos;
import utilidades.LimpaComponente;

public class TelaFormularioPedidos extends javax.swing.JFrame {

    private final LimpaComponente limpar = new LimpaComponente();
    private final SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    private final Connection conn;

    String dataFormatada = sdf.format(new Date());
    double subtotal, total;
    int idFornecedor, idFornecedorCarrinho;
    DefaultTableModel meuPedido;
    List<Integer> idPecaTabela = new ArrayList<>();

    // filtra as peças na tabela pelo fornecedor selecionado
    public void filtrar() {
        String nome = cbNomeFornecedor.getSelectedItem().toString();
        PecasDAO pecasDao = new PecasDAO(conn);
        List<Pecas> lista = pecasDao.filtrarPecasFornecedor(nome);
        DefaultTableModel dados = (DefaultTableModel) tabelaPecasFornecedor.getModel();
        dados.setNumRows(0);
        for (Pecas p : lista) {
            dados.addRow(new Object[]{
                p.getId(),
                p.getFornecedor(),
                p.getNome(),
                p.getDescricao(),
                p.getQuantidade(),
                p.getValorUnidadeFornecedor(),
                p.getValorUnidadeCliente()

            });
        }
    }

    // calcula o valor total da peça no pedido
    private void calcularValorTotalPeca() {
        try {
            double valorFornecedor = Double.parseDouble(txtPrecoUnidadeFornecedor.getText());
            int qtdPedido = Integer.parseInt(txtQtdPedido.getText());
            double valorTotalPeca = valorFornecedor * qtdPedido;

            DecimalFormatSymbols dataBase = new DecimalFormatSymbols(Locale.US);
            DecimalFormat df = new DecimalFormat("0.00", dataBase);
            String valorFormatado = df.format(valorTotalPeca);
            txtValorTotalPeca.setText(valorFormatado);
        } catch (NumberFormatException e) {
            txtValorTotalPeca.setText("");
        }
    }

    // calcula o valor total do pedido
    private void calcularValorTotalPedido(double total) {
        DecimalFormatSymbols dataBase = new DecimalFormatSymbols(Locale.US);
        DecimalFormat df = new DecimalFormat("0.00", dataBase);
        String valorTotalFormatado = df.format(total);
        txtTotalPedido.setText(valorTotalFormatado);
    }

    public void listarPecasFornecedor() {

    }

    public void limparTudo() {
        limpar.limparTabela(tabelaCarrinho);
        limpar.limparTabela(tabelaPecasFornecedor);
        limpar.limparCampos(panelPedido);
        limpar.limparCampos(panelDadosPeca);
        limpar.limparCampos(panelDadosFornecedor);

        subtotal = 0;
        total = 0;
        idFornecedorCarrinho = 0;
        idPecaTabela.clear();

        cbNomeFornecedor.setEnabled(true);
        cbNomeFornecedor.setSelectedIndex(0);
    }

    public TelaFormularioPedidos(Connection conn) {
        initComponents();
        this.conn = conn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelDadosFornecedor = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCnpj = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDataAtual = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmailFornecedor = new javax.swing.JTextField();
        btnPesquisarNomeFornecedor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaPecasFornecedor = new javax.swing.JTable();
        btnLimparTudo = new javax.swing.JButton();
        cbNomeFornecedor = new javax.swing.JComboBox();
        panelDadosPeca = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtIdPeca = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNomePeca = new javax.swing.JTextField();
        txtQtdEstoque = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQtdPedido = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPrecoUnidadeFornecedor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtValorTotalPeca = new javax.swing.JTextField();
        btnAdicionarPeca = new javax.swing.JButton();
        btnLimparPeca = new javax.swing.JButton();
        panelPedido = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaCarrinho = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        txtTotalPedido = new javax.swing.JTextField();
        btnFazerPedido = new javax.swing.JButton();
        btnCancelarPedido = new javax.swing.JButton();
        btnRemoverPecaCarrinho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Formulário de Pedidos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Formulário de Pedidos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        panelDadosFornecedor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Fornecedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel2.setText("CNPJ:");

        txtCnpj.setEditable(false);
        try {
            txtCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCnpj.setEnabled(false);

        jLabel3.setText("Data:");

        txtDataAtual.setEditable(false);
        try {
            txtDataAtual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Nome:");

        jLabel5.setText("E-mail:");

        txtEmailFornecedor.setEditable(false);
        txtEmailFornecedor.setEnabled(false);

        btnPesquisarNomeFornecedor.setText("Pesquisar");
        btnPesquisarNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarNomeFornecedorActionPerformed(evt);
            }
        });

        tabelaPecasFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "FORNECEDOR", "NOME", "DESCRIÇÃO", "QUANTIDADE", "VALOR FORNECEDOR", "VALOR CLIENTE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaPecasFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaPecasFornecedorMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaPecasFornecedor);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnLimparTudo.setText("Limpar");
        btnLimparTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparTudoActionPerformed(evt);
            }
        });

        cbNomeFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbNomeFornecedorAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout panelDadosFornecedorLayout = new javax.swing.GroupLayout(panelDadosFornecedor);
        panelDadosFornecedor.setLayout(panelDadosFornecedorLayout);
        panelDadosFornecedorLayout.setHorizontalGroup(
            panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                .addGap(97, 97, 97))
                            .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnPesquisarNomeFornecedor)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparTudo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)))))
                .addContainerGap())
        );
        panelDadosFornecedorLayout.setVerticalGroup(
            panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnPesquisarNomeFornecedor)
                        .addComponent(btnLimparTudo))
                    .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtDataAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDadosPeca.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Peça", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel6.setText("Id:");

        txtIdPeca.setEditable(false);
        txtIdPeca.setEnabled(false);

        jLabel7.setText("Nome:");

        jLabel8.setText("Quantidade Estoque:");

        txtNomePeca.setEditable(false);
        txtNomePeca.setEnabled(false);

        txtQtdEstoque.setEditable(false);
        txtQtdEstoque.setEnabled(false);

        jLabel9.setText("Quantidade Pedido:");

        txtQtdPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(java.awt.event.KeyEvent e) {
                char c = e.getKeyChar();
                if (!Character.isDigit(c)) {
                    e.consume();
                }
                if (txtQtdPedido.getText().length() >= 6) {
                    e.consume();
                }
            }
        });
        txtQtdPedido.setEnabled(false);
        txtQtdPedido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtdPedidoKeyReleased(evt);
            }
        });

        jLabel10.setText("Preço Unidade:");

        txtPrecoUnidadeFornecedor.setEditable(false);
        txtPrecoUnidadeFornecedor.setEnabled(false);

        jLabel11.setText("Valor Total:");

        txtValorTotalPeca.setEditable(false);
        txtValorTotalPeca.setEnabled(false);

        btnAdicionarPeca.setText("Adicionar");
        btnAdicionarPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarPecaActionPerformed(evt);
            }
        });

        btnLimparPeca.setText("Limpar");
        btnLimparPeca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparPecaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDadosPecaLayout = new javax.swing.GroupLayout(panelDadosPeca);
        panelDadosPeca.setLayout(panelDadosPecaLayout);
        panelDadosPecaLayout.setHorizontalGroup(
            panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDadosPecaLayout.createSequentialGroup()
                        .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtQtdEstoque))
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorTotalPeca))
                            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPrecoUnidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panelDadosPecaLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdPeca, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAdicionarPeca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimparPeca)
                .addGap(70, 70, 70))
        );
        panelDadosPecaLayout.setVerticalGroup(
            panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDadosPecaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtIdPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtNomePeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(txtPrecoUnidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtQtdPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtValorTotalPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(panelDadosPecaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarPeca)
                    .addComponent(btnLimparPeca))
                .addGap(32, 32, 32))
        );

        panelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tabelaCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PEÇA", "QUANTIDADE", "PREÇO", "SUBTOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaCarrinho);

        jLabel12.setText("Total do Pedido:");

        txtTotalPedido.setEditable(false);
        txtTotalPedido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTotalPedido.setEnabled(false);

        btnFazerPedido.setText("Fazer Pedido");
        btnFazerPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFazerPedidoActionPerformed(evt);
            }
        });

        btnCancelarPedido.setText("Cancelar Pedido");
        btnCancelarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPedidoActionPerformed(evt);
            }
        });

        btnRemoverPecaCarrinho.setText("Remover");
        btnRemoverPecaCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverPecaCarrinhoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPedidoLayout = new javax.swing.GroupLayout(panelPedido);
        panelPedido.setLayout(panelPedidoLayout);
        panelPedidoLayout.setHorizontalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCancelarPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFazerPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 25, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(btnRemoverPecaCarrinho)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPedidoLayout.setVerticalGroup(
            panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPedidoLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemoverPecaCarrinho)
                .addGap(11, 11, 11)
                .addGroup(panelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPedidoLayout.createSequentialGroup()
                        .addComponent(btnFazerPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(btnCancelarPedido))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTotalPedido, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelDadosPeca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDadosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDadosPeca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarNomeFornecedorActionPerformed
        // pesquisa o fornecedor no banco de dados com base no item selecionado no comboBox
        String nome = cbNomeFornecedor.getSelectedItem().toString();
        // verifica se o nome é diferente do valor padrão
        if (nome.equals("Selecione o fornecedor")) {
            return;
        }

        FornecedoresDAO fornecedoresDao = new FornecedoresDAO(conn);
        Fornecedores fornecedor = fornecedoresDao.buscarNomeFornecedor(nome);
        // verifica se o fornecedor foi encontrado no banco de dados e filtra as peças na tabela
        if (fornecedor.getRazaoSocial() != null) {
            txtCnpj.setText(fornecedor.getCnpj());
            txtEmailFornecedor.setText(fornecedor.getEmail());
            cbNomeFornecedor.setEnabled(false);
            filtrar();
        } else {
            JOptionPane.showMessageDialog(null, "Fornecedor não encontrado para o nome concedido!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarNomeFornecedorActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // atualiza a data ao abrir a janela
        txtDataAtual.setText(dataFormatada);
    }//GEN-LAST:event_formWindowActivated

    private void tabelaPecasFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaPecasFornecedorMouseClicked
        // transfere os dados da linha selecionada na tabela para os campos
        txtIdPeca.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 0).toString());
        txtNomePeca.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 2).toString());
        txtQtdEstoque.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 4).toString());
        txtPrecoUnidadeFornecedor.setText(tabelaPecasFornecedor.getValueAt(tabelaPecasFornecedor.getSelectedRow(), 5).toString());
        txtQtdPedido.setEnabled(true);
        txtQtdPedido.requestFocus();
    }//GEN-LAST:event_tabelaPecasFornecedorMouseClicked

    private void btnLimparPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparPecaActionPerformed
        // limpa os campos do painel
        limpar.limparCampos(panelDadosPeca);
        txtQtdPedido.setEnabled(false);
    }//GEN-LAST:event_btnLimparPecaActionPerformed

    private void btnLimparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparTudoActionPerformed
        // após confirmação, reseta todos os dados menos a data
        int opcao = JOptionPane.showConfirmDialog(null, """
                Ao limpar o fornecedor selecionado, 
                todos os itens salvos no carrinho serão limpos.
                Você tem certeza que quer prosseguir?
                """,
                "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            limparTudo();
        }
    }//GEN-LAST:event_btnLimparTudoActionPerformed

    private void btnAdicionarPecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarPecaActionPerformed
        // adiciona ou atualiza peça na tabela
        String nome = txtNomePeca.getText();
        PecasDAO pecasDao = new PecasDAO(conn);
        Pecas peca = pecasDao.buscarPeca(nome);

        //verifica se a peça foi encontrada no banco de dados antes de continuar
        if (peca != null) {
            idFornecedor = peca.getFornecedor().getId();
            int idFornecedorPeca = peca.getFornecedor().getId();
            int idPeca = peca.getId();
            boolean temNoCarrinho = idPecaTabela.contains(idPeca);
            String qtd = txtQtdPedido.getText();

            // impede que uma peça sem quantidade definida seja adicionada ao pedido
            if (qtd.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Adicione a quantidade de peças no pedido!", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }
            // define o fornecedor da tabela com base na primeira peça adicionada
            if (idFornecedorCarrinho == 0) {
                idFornecedorCarrinho = idFornecedor;
            }
            // pega o valor total da peça e soma ao total
            subtotal = Math.round(Double.parseDouble(txtValorTotalPeca.getText()) * 100.0) / 100.0;
            total += subtotal;
            calcularValorTotalPedido(total);

            meuPedido = (DefaultTableModel) tabelaCarrinho.getModel();

            // adiciona a nova peça no carrinho e atualiza o valor total do pedido
            if (idFornecedorPeca == idFornecedorCarrinho && !temNoCarrinho) {
                txtTotalPedido.setText(String.valueOf(total));
                idPecaTabela.add(idPeca);
                meuPedido.addRow(new Object[]{
                    txtIdPeca.getText(),
                    txtNomePeca.getText(),
                    txtQtdPedido.getText(),
                    txtPrecoUnidadeFornecedor.getText(),
                    subtotal
                });
                // se a peça já estiver no carrinho, atualiza a quantidade e subtotal
            } else if (temNoCarrinho) {
                // percorre as linhas na tabela
                for (int i = 0, linhasNaTabela = meuPedido.getRowCount(); i < linhasNaTabela; i++) {
                    int idNaTabela = Integer.parseInt(meuPedido.getValueAt(i, 0).toString());
                    // verifica se o id da peça corresponde ao id da peça no carrinho e atualiza os dados
                    if (idNaTabela == idPeca) {
                        int qtdAtual = Integer.parseInt(meuPedido.getValueAt(i, 2).toString());
                        int qtdNova = qtdAtual + Integer.parseInt(qtd);
                        meuPedido.setValueAt(qtdNova, i, 2);

                        double precoUnitario = Double.parseDouble(meuPedido.getValueAt(i, 3).toString());
                        double novoSubtotal = qtdNova * precoUnitario;
                        novoSubtotal = Math.round(novoSubtotal * 100.0) / 100.0;
                        meuPedido.setValueAt(novoSubtotal, i, 4);
                        break;
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "A peça não pode ser adicionada ao carrinho pois o fornecedor é diferente das outras!", "Atenção", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível adicionar ao carrinho.\n Faltam informações.", "Erro", JOptionPane.ERROR_MESSAGE);
        }
        limpar.limparCampos(panelDadosPeca);
        txtQtdPedido.setEnabled(false);
    }//GEN-LAST:event_btnAdicionarPecaActionPerformed

    private void txtQtdPedidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtdPedidoKeyReleased
        // faz o calculo ao adicionar digitos
        calcularValorTotalPeca();
    }//GEN-LAST:event_txtQtdPedidoKeyReleased

    private void cbNomeFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbNomeFornecedorAncestorAdded
        // carrega todos os fornecedores existentes no banco de dados no comboBox
        FornecedoresDAO fornecedoresDao = new FornecedoresDAO(conn);
        List<Fornecedores> lista = fornecedoresDao.listar();
        cbNomeFornecedor.removeAllItems();
        cbNomeFornecedor.addItem("Selecione o fornecedor");
        for (Fornecedores f : lista) {
            cbNomeFornecedor.addItem(f);
        }
    }//GEN-LAST:event_cbNomeFornecedorAncestorAdded

    private void btnFazerPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFazerPedidoActionPerformed
        Pedidos pedido = new Pedidos();
        Fornecedores fornecedor = (Fornecedores) cbNomeFornecedor.getSelectedItem();
        pedido.setFornecedor(fornecedor);

        Date agora = new Date();
        pedido.setData(agora);

        pedido.setValorTotal(total);
        pedido.setStatus(Pedidos.Status.PENDENTE);

        PedidosDAO pedidosDao = new PedidosDAO(conn);
        pedidosDao.salvar(pedido);
        pedido.setId(pedidosDao.retornaUltimoIdVenda());
        JOptionPane.showMessageDialog(null, "ID do último pedido!" + pedido.getId());

        int quantidadeItensCarrinho = meuPedido.getRowCount();
        for (int i = 0; i < quantidadeItensCarrinho; i++) {
            Pecas peca = new Pecas();
            PecasPedidos item = new PecasPedidos();

            item.setPedido(pedido);
            peca.setId(Integer.parseInt(meuPedido.getValueAt(i, 0).toString()));

            item.setPeca(peca);
            item.setQuantidade(Integer.parseInt(meuPedido.getValueAt(i, 2).toString()));

            item.setSubtotal(Double.parseDouble(meuPedido.getValueAt(i, 4).toString()));

            PecasPedidosDAO pecasPedidosDao = new PecasPedidosDAO(conn);
            pecasPedidosDao.salvar(item);
        }
        limparTudo();

    }//GEN-LAST:event_btnFazerPedidoActionPerformed

    private void btnCancelarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPedidoActionPerformed
        // após confirmação limpa os dados
        int opcao = JOptionPane.showConfirmDialog(null, "Você tem certeza que quer limpar o carrinho do pedido?", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (opcao == JOptionPane.YES_OPTION) {
            limparTudo();
        }
    }//GEN-LAST:event_btnCancelarPedidoActionPerformed

    private void btnRemoverPecaCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverPecaCarrinhoActionPerformed
        // verifica se uma linha da tabela está pressionada
        int linhaSelecionada = tabelaCarrinho.getSelectedRow();
        if (linhaSelecionada < 0) {
            JOptionPane.showMessageDialog(null, "Selecione um item da tabela.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int idPeca = Integer.parseInt(tabelaCarrinho.getValueAt(linhaSelecionada, 0).toString());
        int opcao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover esta peça?", "Aviso", JOptionPane.YES_NO_OPTION, JOptionPane.YES_NO_OPTION);
        // se sim, deleta a linha da tabela e diminui os valores
        if (opcao == JOptionPane.YES_OPTION) {
            meuPedido = (DefaultTableModel) tabelaCarrinho.getModel();
            // percorre as linhas na tabela e remove o id da peça da lista de controle
            for (int i = 0, linhasNaTabela = meuPedido.getRowCount(); i < linhasNaTabela; i++) {
                int idNaTabela = Integer.parseInt(meuPedido.getValueAt(i, 0).toString());
                if (idPeca == idNaTabela) {
                    idPecaTabela.remove(Integer.valueOf(idPeca));
                    idPecaTabela.clear();
                    break;
                }
            }
            double subtotalRemovido = Double.parseDouble(tabelaCarrinho.getValueAt(linhaSelecionada, 4).toString());
            total -= subtotalRemovido;
            calcularValorTotalPedido(total);
            meuPedido.removeRow(linhaSelecionada);
            /*if (meuPedido.getRowCount() == 0) {
                
            }*/
        }
    }//GEN-LAST:event_btnRemoverPecaCarrinhoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFormularioPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Connection conn = MySQLConnection.getConnection();
                    new TelaFormularioPedidos(conn).setVisible(true);
                } catch (Exception e) {
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarPeca;
    private javax.swing.JButton btnCancelarPedido;
    private javax.swing.JButton btnFazerPedido;
    private javax.swing.JButton btnLimparPeca;
    private javax.swing.JButton btnLimparTudo;
    private javax.swing.JButton btnPesquisarNomeFornecedor;
    private javax.swing.JButton btnRemoverPecaCarrinho;
    private javax.swing.JComboBox cbNomeFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelDadosFornecedor;
    private javax.swing.JPanel panelDadosPeca;
    private javax.swing.JPanel panelPedido;
    private javax.swing.JTable tabelaCarrinho;
    private javax.swing.JTable tabelaPecasFornecedor;
    private javax.swing.JFormattedTextField txtCnpj;
    private javax.swing.JFormattedTextField txtDataAtual;
    private javax.swing.JTextField txtEmailFornecedor;
    private javax.swing.JTextField txtIdPeca;
    private javax.swing.JTextField txtNomePeca;
    private javax.swing.JTextField txtPrecoUnidadeFornecedor;
    private javax.swing.JTextField txtQtdEstoque;
    private javax.swing.JTextField txtQtdPedido;
    private javax.swing.JTextField txtTotalPedido;
    private javax.swing.JTextField txtValorTotalPeca;
    // End of variables declaration//GEN-END:variables

}
